blueprint:
  name: Door Sensor-activated actions
  description: Execute any action when a door is opened.
  domain: automation
  input:
    doorsensor_entity:
      name: Door Sensor
      selector:
        entity:
          domain: binary_sensor
    opening_action:
      name: Opening
      description: Opening is active
      default: []
      selector:
        action: {}
    closing_action:
      name: Closing
      description: Closing is active
      default: []
      selector:
        action: {}

mode: single
max_exceeded: silent

trigger:
  platform: state
  entity_id: !input doorsensor_entity

variables:
  command: '{{ trigger.to_state.state }}'

condition:
  - condition: template
    value_template: "{{ command != ''}}"

action:
- choose:
  - conditions:
     - '{{ command == ''on'' }}'
     sequence: !input opening_action
  - conditions:
     - '{{ command == ''off'' }}'
     sequence: !input closing_action
