blueprint:
  name: Door Sensor-activated actions (zigbee2mqtt)
  description: Execute any action when a door is opened.
  domain: automation
  input:
    source_selector:
      name: Door Sensor
      default:
      selector:
        entity:
          domain: binary_sensor
          multiple: false
    target_opening_action:
      name: Opening action
      description: When contacts are distant.
      default:
      selector:
        action: {}
    target_closing_action:
      name: Closing action
      description: When contacts are very close.
      default:
      selector:
        action: {}
mode: single
max_exceeded: silent
trigger:
  platform: state
  entity_id: !input 'source_selector'
action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ trigger.to_state.attributes.contact }}'
      sequence: !input 'target_closing_action'
    - conditions:
      - condition: template
        value_template: '{{ not (trigger.to_state.attributes.contact) }}'
      sequence: !input 'target_opening_action'
    default: []
